runtime: nodejs18

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 2

env_variables:
  DB_HOST: "34.50.77.131"
  DB_USER: "root"
  DB_PASSWORD: "capstone123"
  DB_NAME: "capstones"
  JWT_SECRET: "123SatuDuaTiga"
